
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost/blog?characterEncoding=utf-8
  jpa:
    show-sql: true
  jackson:
    default-property-inclusion: non_null
#  servlet:
#    multipart:
#      location: classpath:
server:
  port: 80
mybatis:
  type-aliases-package: com.seven.Blog.pojo
  mapper-locations: classpath:mybatis/mappers/*.xml

