spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/blog?characterEncoding=utf-8&allowMultiQueries=true

    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 2
    minIdle: 2
    maxActive: 10
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: true
    testOnReturn: false
    poolPreparedStatements: true
    filters: stat
    maxPoolPreparedStatementPerConnectionSize: 20
    useGlobalDataSourceStat: true
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
    loginUsername: admin
    loginPassword: admin
  mail:
    host: smtp.qq.com
    username:
    password:
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          ssl:
            trust: smtp.qq.com
          socketFactory:
            class: javax.net.ssl.SSLSocketFactory
            port: 465
          auth: true
          starttls:
            enable: true
            required: true
  redis:
    host: 127.0.0.1
    password: 123456
    database: 0
    port: 6379
  session:
    store-type: redis
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    virtual-host: test
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
    username: root
    password: root
    listener:
      simple:
        # 消费方手动确认消费
        acknowledge-mode: manual
logging:
  level:
    cn:
      ntshare:
        Blog:
          dao: debug
log:
  path: D:/Develop/Java/Blog/logs

