spring:
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null

server:
  port: 8100
  servlet:
    path: /blog/v1

mybatis:
  type-aliases-package: cn.ntshare.Blog.pojo
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  support-methods-arguments: true
  auto-dialect: mysql



