spring:
  application:
    name: zuul
  profiles:
    active: dev
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka/
zuul:
  prefix: /blog/v1
  routes:
    backend:
      path: /backend/**
      serviceId: blog-backend
      sensitive-headers:
      custom-sensitive-headers: true
    file:
      path: /file/**
      serviceId: blog-file
      sensitive-headers:
      custom-sensitive-headers: true
    frontend:
      path: /**
      serviceId: blog-frontend