spring:
  application:
    name: zuul
server:
  port: 8100
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka/
zuul:
  prefix: /blog/v1
  routes:
    frontend:
      path: /frontend/**
      serviceId: blog-frontend