spring:
  application:
    name: blog-backend
  profiles:
    active: dev
  jackson:
    default-property-inclusion: non_null
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: test
    password: test
    virtual-host: blog
    # 开启发送确认
    publisher-confirms: true
    # 开启发送失败退回
    publisher-returns: true
server:
  port: 8104
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8101/eureka/
mybatis:
  type-aliases-package: cn.ntshare.blog.pojo
  mapper-locations: classpath:mybatis/mappers/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
  reasonable: true
  support-methods-arguments: true
  auto-dialect: mysql
